### ISSUE TITLE
Future Development Plans for ml_collections

### ISSUE THREAD

**Issue by ruidazeng** [google/ml_collections#40]
Just wondering, are there any new features or updates or new releases coming soon, or is the project wrapping up and going into the archives soon?

**Comment by Conchylicultor** [comment]
For sure it's not going to the archives anytime soon. I'm planing to push a new version this week: https://github.com/google/ml_collections/pull/38

For context, as part of `kauldron`, we developed a wrapper around `ConfigDict` which allow to turn any Python class or function into configurable. See a demo here: https://github.com/google-research/kauldron/blob/main/kauldron/konfig/docs/demo.ipynb

**Comment by ruidazeng** [comment]
> For sure it's not going to the archives anytime soon. I'm planing to push a new version this week: [#38](https://github.com/google/ml_collections/pull/38)
> 
> For context, as part of `kauldron`, we developed a wrapper around `ConfigDict` which allow to turn any Python class or function into configurable. See a demo here: https://github.com/google-research/kauldron/blob/main/kauldron/konfig/docs/demo.ipynb

Awesome to hear. What makes kauldron unique over the other libraries for machine learning training.
